[package]
name = "rust-sample"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
lambda_http = "0.6"
aws-config = "0.46.0"
aws-sdk-dynamodb = "0.16.0"
